language: ruby
script: 'bundle exec rake'
rvm:
  - 2.2.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head
services:
  - redis-server
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
